#!/usr/bin/env node
/**
 * GEO build — regenerates AI/SEO-discoverable artifacts from the source JSON.
 *
 * Inputs (repo root):
 *   - glossary-data.json   (array of { slug, title, sections:[{title,text}] })
 *   - data.json            (array of stories { story_id, title, category, story_text, takeaway, why_now, sent_at })
 *
 * Outputs (repo root):
 *   - glossary.html        (JSON-LD DefinedTermSet block refreshed in place)
 *   - stories.html         (JSON-LD Blog block refreshed in place)
 *   - llms-full.txt        (full machine-readable content)
 *
 * llms.txt is intentionally NOT touched (it is hand-written, content-agnostic).
 *
 * Idempotent: safe to run on every push. Only rewrites the JSON-LD block,
 * anchored on the `<!-- Structured Data (GEO/SEO) -->` comment (falls back to
 * inserting before </head> if the anchor is missing).
 */
const fs = require('fs');

const SITE = 'https://piacradar.eu';
const clean = (t) => (t || '').replace(/\s+/g, ' ').trim();
const shorten = (t, n) => {
  t = clean(t);
  if (t.length <= n) return t;
  return t.slice(0, n).replace(/\s+\S*$/, '') + '…';
};
const readJSON = (p) => JSON.parse(fs.readFileSync(p, 'utf8'));

// ---------- GLOSSARY JSON-LD (DefinedTermSet) ----------
function glossaryLD(glossary) {
  const terms = glossary.map((e) => {
    const secs = Array.isArray(e.sections) ? e.sections : [];
    const desc = secs.length && secs[0] && typeof secs[0] === 'object' ? secs[0].text : '';
    return {
      '@type': 'DefinedTerm',
      name: e.title,
      url: `${SITE}/glossary.html#${e.slug}`,
      description: shorten(desc, 180),
      inDefinedTermSet: `${SITE}/glossary.html`,
    };
  });
  return {
    '@context': 'https://schema.org',
    '@type': 'DefinedTermSet',
    name: 'Piacradar Pénzügyi Szótár',
    url: `${SITE}/glossary.html`,
    description:
      '100+ pénzügyi és tőzsdei fogalom magyarázata befektetői kontextussal: CPI, GDP, VIX, EPS és sok más.',
    inLanguage: 'hu',
    hasDefinedTerm: terms,
  };
}

// ---------- STORIES JSON-LD (Blog) ----------
function storiesLD(stories) {
  const posts = stories.map((st) => {
    const post = {
      '@type': 'BlogPosting',
      headline: st.title,
      description: shorten(st.takeaway || st.story_text || '', 200),
      articleSection: st.category || '',
      url: `${SITE}/stories.html#${st.story_id || ''}`,
      inLanguage: 'hu',
      isPartOf: { '@type': 'Blog', name: 'Szombati Történetek', url: `${SITE}/stories.html` },
      publisher: { '@type': 'Organization', name: 'Piacradar', url: `${SITE}/` },
    };
    // Only emit datePublished when a real date exists
    if (st.sent_at && String(st.sent_at).toLowerCase() !== 'none') {
      post.datePublished = st.sent_at;
    }
    return post;
  });
  return {
    '@context': 'https://schema.org',
    '@type': 'Blog',
    name: 'Szombati Történetek',
    url: `${SITE}/stories.html`,
    description:
      'Heti történetek piaci összeomlásokról, tőzsdei legendákról és befektetői tanulságokról — magyarul.',
    inLanguage: 'hu',
    blogPost: posts,
  };
}

// ---------- Embed/replace JSON-LD block in an HTML file ----------
function embedLD(path, ld) {
  let html = fs.readFileSync(path, 'utf8');
  const block =
    '<!-- Structured Data (GEO/SEO) — auto-generated by geo-build.js, do not edit by hand -->\n  ' +
    '<script type="application/ld+json">\n' +
    JSON.stringify(ld, null, 2) +
    '\n  </script>';
  // Anchor: existing GEO comment + following ld+json script (any variant)
  const re = /<!-- Structured Data \(GEO\/SEO\)[^>]*-->\s*<script type="application\/ld\+json">[\s\S]*?<\/script>/;
  if (re.test(html)) {
    html = html.replace(re, block);
  } else {
    // Fallback: insert before </head>
    html = html.replace('</head>', '  ' + block + '\n</head>');
  }
  fs.writeFileSync(path, html);
  // validate JSON
  JSON.parse(JSON.stringify(ld));
  return html.length;
}

// ---------- llms-full.txt (complete machine-readable content) ----------
function buildLlmsFull(glossary, stories) {
  const out = [];
  out.push('# Piacradar — teljes tartalom (AI/LLM olvasásra)\n');
  out.push(
    `> Ez a fájl a Piacradar teljes edukációs tartalmát tartalmazza gépi olvasásra: a Pénzügyi Szótár összes fogalma és a Szombati Történetek teljes szövege. Forrás és kapcsolat: ${SITE}/ · Telegram: https://t.me/+Mk5bfbCfUf1lMGE0 · Készítő: Tamás Kovács (https://tamaskovacs.eu).\n`
  );
  out.push(
    'A tartalmak kizárólag általános tájékoztatási célt szolgálnak, nem minősülnek befektetési tanácsadásnak.\n'
  );

  out.push(`\n# Pénzügyi Szótár (${glossary.length} fogalom)\n`);
  out.push(`Forrás: ${SITE}/glossary.html\n`);
  const sorted = [...glossary].sort((a, b) =>
    a.title.toLowerCase().localeCompare(b.title.toLowerCase(), 'hu')
  );
  for (const e of sorted) {
    out.push(`\n## ${e.title}`);
    out.push(`Hivatkozás: ${SITE}/glossary.html#${e.slug}`);
    for (const sec of e.sections || []) {
      if (sec && typeof sec === 'object') {
        const st = clean(sec.title);
        const tx = clean(sec.text);
        if (st && tx) out.push(`\n**${st}** ${tx}`);
        else if (tx) out.push(`\n${tx}`);
      }
    }
  }

  out.push(`\n\n# Szombati Történetek (${stories.length} történet)\n`);
  out.push(`Forrás: ${SITE}/stories.html\n`);
  for (const st of stories) {
    out.push(`\n## ${clean(st.title)}`);
    const meta = [];
    if (st.category) meta.push(`Kategória: ${clean(st.category)}`);
    meta.push(`Hivatkozás: ${SITE}/stories.html#${st.story_id || ''}`);
    out.push(meta.join(' · '));
    if (st.story_text) out.push(`\n${clean(st.story_text)}`);
    if (st.takeaway) out.push(`\n**Tanulság:** ${clean(st.takeaway)}`);
    if (st.why_now) out.push(`\n**Miért aktuális:** ${clean(st.why_now)}`);
  }
  return out.join('\n') + '\n';
}

// ---------- main ----------
function main() {
  const glossary = readJSON('glossary-data.json');
  const stories = readJSON('data.json');

  const gLen = embedLD('glossary.html', glossaryLD(glossary));
  const sLen = embedLD('stories.html', storiesLD(stories));

  const full = buildLlmsFull(glossary, stories);
  fs.writeFileSync('llms-full.txt', full);

  console.log(`glossary.html: ${glossary.length} terms embedded (${gLen} bytes)`);
  console.log(`stories.html: ${stories.length} posts embedded (${sLen} bytes)`);
  console.log(`llms-full.txt: ${full.length} bytes`);
}

main();
